// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class Comment
{
    public int ID { get; set; }

    public string AuthorName { get; set; }

    public string Content { get; set; }
}