// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models;

public partial class Comment
{
    public int ID { get; set; }

    [Required, MaxLength(50)]
    public string AuthorName { get; set; }

    [Required, MaxLength(500)]
    public string Content { get; set; }

}